/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 17 00:30:32 GMT 2019
 */

package com.desafio.desafiob2w.resource.response;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Status_ESTest extends Status_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Status[] statusArray0 = Status.values();
      assertEquals(3, statusArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Status status0 = Status.valueOf("INTERNAL_ERROR");
      assertEquals("An error occurred", status0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Status status0 = Status.NOT_FOUND;
      String string0 = status0.getStatusCode();
      assertEquals("The requested resource was not found", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Status status0 = Status.NOT_FOUND;
      String string0 = status0.toString();
      assertEquals("The requested resource was not found", string0);
  }
}
